# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and push docker image on docker hub
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shadikkhan/git-action-demo
        tag: v1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push docker image on GCR
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: gcp-taining-290100/git-action-demo
        tag: v1
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_PASSWORD }}
